blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import HomeView

from django.conf.urls.static import static
from django.conf import settings

from blog.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),

    # 아래 인증 URL 3개 추가

    # 장고 Auth앱의 URLCONF에는 /login/, /logout/처럼 저장되어 있으므로
    # 그 앞에 URL 추가를 원한다면 아래와 같이 이를 표시해야 함. -> /accounts/login/ 등이 됨.
    path('accounts/', include('django.contrib.auth.urls')),

    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),


    path('', HomeView.as_view(), name='home'),

    path('blog/', include('blogapp.urls')),
    path('bookmark/', include('bookmarkapp.urls')),
    path('photo/', include('photo.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

# static 함수의 형식은 다음과 같습니다.
# static(prefix(접두사), view=django.views.static.serve, **kwargs)

blog/bookmarkapp/urls.py
from django.contrib import admin
from django.urls import path
from bookmarkapp import views

app_name = 'bookmark'
urlpatterns = [
#
#     # class-based views
    path('', views.BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),
    # 추가
    path('add/', views.BookmarkCreateView.as_view(), name='add',),
    path('change/', views.BookmarkChangeLV.as_view(), name='change',),
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name='update',),
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name='delete',),
]

blog/bookmarkapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True, )

    def __str__(self):
        return self.title

blog/bookmarkapp/views.py
from django.views.generic import ListView, DetailView
from bookmarkapp.models import Bookmark

from django.shortcuts import render

# 추가
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from blog.views import OwnerOnlyMixin ###수정?

class BookmarkLV(ListView):
    model = Bookmark

class BookmarkDV(DetailView):
    model = Bookmark

class BookmarkCreateView(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)

class BookmarkChangeLV(LoginRequiredMixin, ListView):
    template_name = 'bookmarkapp/bookmark_change_list.html'

    def get_queryset(self):
        return Bookmark.objects.filter(owner=self.request.user)

class BookmarkUpdateView(LoginRequiredMixin, UpdateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

class BookmarkDeleteView(OwnerOnlyMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

blog/bookmarkapp/templates/bookmarkapp/bookmark_change_list.html
{% extends "base.html" %}
{% block title %}bookmark_change_list.html{% endblock %}
{% block content %}
<h1>Bookmark Change - {{ user }}</h1>
<br>
<table calss="table table-bordered table-condensed table-striped">
<thead>
<tr calss="table-primary">
    <th>Title</th>
    <th>Url</th>
    <th>Owner</th>
    <th>Update</th>
    <th>Delete</th>
</tr>
</thead>

<tbody>
{% for item in object_list %}
<tr>
    <td>{{ item.title }}</td>
    <td>{{ item.url }}</td>
    <td>{{ item.owner }}</td>
    <td><a href="{% url 'bookmark:update' item.id %}">Update</a></td>
    <td><a href="{% url 'bookmark:delete' item.id %}">Delete</a></td>
</tr>
{% endfor %}
</tbody>
</table>
{% endblock %}

blog/bookmarkapp/templates/bookmarkapp/bookmark_confirm_delete.html
{% extends "base.html" %}
{% block title %}bookmark_confirm_delete.html{% endblock %}


{% block content %}
<h1>Bookmark Delete</h1>
<br>

<form action="." method="post">{% csrf_token %}
<p>Are you sure you want to delete "{{ object }}" ?</p>
    <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
</form>

{% endblock %}

blog/bookmarkapp/templates/bookmarkapp/bookmark_detail.html
{% extends "base.html" %}
{% block title %}Django Bookmark Detail{% endblock %}

{% block content %}
<div id="content">

    <h1>{{ object.title }}</h1>

    <ul>
        <li>URL: <a href="{{ object.url }}">{{ object.url }}</a></li>
    </ul>
</div>
{% endblock %}

blog/bookmarkapp/templates/bookmarkapp/bookmark_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}bookmark_form_html{% endblock %}

{% block content %}
<h1>Bookmark Create/Update - {{ user }}</h1>
<p class="font-italic">This is a creation or update form for your bookmark.</p>

{% if form.errors %}
<div class="alert alert-danger">
    <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
    {{ form.errors }}
</div>
{% endif %}

<form action="." method="post" class="card pt-3">{% csrf_token %}
    <div class="form-group row">
        {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-5">
            {{ form.title|add_class:"form-control"|attr:"autofocus" }}
        </div>

    <div class="form-group row">
        {{ form.url|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
        <div class="col-sm-5">
            {{ form.url|add_class:"form-control" }}
        </div>
    </div>

    <div class="form-group">
        <div calss="offset-sm-2 col-sm-5">
            <input type="submit" value="Submit" class="btn btn-info"/>
        </div>
    </div>

</form>

{% endblock %}

blog/bookmarkapp/templates/bookmarkapp/bookmark_list.html
{% extends "base.html" %}
    {% block title %}Django Bookmark List{% endblock %}
{% block content %}
<div id="content">
    <h1>Bookmark List</h1>

    <ul>
        {% for bookmark in object_list %}
            <li><a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a></li>
        {% endfor %}
    </ul>
</div>
{% endblock %}