blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from blog.views import HomeView

from django.conf.urls.static import static
from django.conf import settings

from blog.views import UserCreateView, UserCreateDoneTV

urlpatterns = [
    path('admin/', admin.site.urls),

    # 아래 인증 URL 3개 추가

    # 장고 Auth앱의 URLCONF에는 /login/, /logout/처럼 저장되어 있으므로
    # 그 앞에 URL 추가를 원한다면 아래와 같이 이를 표시해야 함. -> /accounts/login/ 등이 됨.
    path('accounts/', include('django.contrib.auth.urls')),

    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),


    path('', HomeView.as_view(), name='home'),

    path('blog/', include('blogapp.urls')),
    path('bookmark/', include('bookmarkapp.urls')),
    path('photo/', include('photo.urls')),

] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

# static 함수의 형식은 다음과 같습니다.
# static(prefix(접두사), view=django.views.static.serve, **kwargs)

blog/blogapp/urls.py
from django.urls import path, re_path
from blogapp import views

app_name = 'blog'
urlpatterns = [

    path('', views.PostLV.as_view(), name='index'),
    path('post/', views.PostLV.as_view(), name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)/$', views.PostDV.as_view(), name='post_detail'),
    path('archive/', views.PostAV.as_view(), name='post_archive'),
    path('archive/<int:year>/', views.PostYAV.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>/', views.PostMAV.as_view(), name='post_month_archive'),

    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDAV.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTAV.as_view(), name='post_today_archive'),

    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    # example : /blog/tag/tagname/
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    path('search/', views.SearchFormView.as_view(), name='search'),
    # 추가
    path('add/', views.PostCreateView.as_view(), name='add', ),
    path('change/', views.PostChangeLV.as_view(), name='change', ),
    path('<int:pk>/update/', views.PostUpdateView.as_view(), name='update', ),
    path('<int:pk>/delete/', views.PostDeleteView.as_view(), name='delete', ),
]

blog/bookmarkapp/urls.py
from django.contrib import admin
from django.urls import path
from bookmarkapp import views

app_name = 'bookmark'
urlpatterns = [
#
#     # class-based views
    path('', views.BookmarkLV.as_view(), name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),
    # 추가
    path('add/', views.BookmarkCreateView.as_view(), name='add',),
    path('change/', views.BookmarkChangeLV.as_view(), name='change',),
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name='update',),
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name='delete',),
]

blog/photo/urls.py
from django.urls import path
from photo import views

app_name = 'photo'
urlpatterns = [
    path('', views.AlbumLV.as_view(), name='index'),
    path('album', views.AlbumLV.as_view(), name='album_list'),
    path('album/<int:pk>/', views.AlbumDV.as_view(), name='album_detail'),
    path('photo/<int:pk>/', views.PhotoDV.as_view(), name='photo_detail'),

    #추가
    path('album/add/', views.AlbumPhotoCV.as_view(), name='album_add'),
    path('album/change/', views.AlbumChangeLV.as_view(), name='album_change'),
    # example : /photo/album/99/update bottom
    path('album/<int:pk>/update/', views.AlbumPhotoUV.as_view(), name='album_update'),
    path('album/<int:pk>/delete/', views.AlbumDelV.as_view(), name='album_delete'),

    path('photo/add/', views.PhotoCV.as_view(), name='photo_add'),
    path('photo/change/', views.PhotoChangeLV.as_view(), name='photo_change'),

    path('photo/<int:pk>/update/', views.PhotoUV.as_view(), name='photo_update'),
    path('photo/<int:pk>/delete/', views.PhotoDelV.as_view(), name='photo_delete'),

]

blog/blog/views.py
from django.views.generic import TemplateView

# 아래 3줄 추가
from django.views.generic import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

# 추가 // view 진입단계에서 적절한 권한을 갖추었는지 판별하기 위한 클래스 임포트
from django.contrib.auth.mixins import AccessMixin


class HomeView(TemplateView):
    template_name = 'home.html'

#--- User Creation
class UserCreateView(CreateView):
    template_name = 'registration/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('register_done')

class UserCreateDoneTV(TemplateView):
    template_name = 'registration/register_done.html'

# 아래 믹스인 클래스 추가
class OwnerOnlyMixin(AccessMixin):
    raise_exception = True
    permission_denied_message = "Owner only can update/delete the object"

    def dispatch(self, request, *args, **kwargs):
        obj = self.get_object()
        if request.user != obj.owner:
            return self.handle_no_permission()
        return super().dispatch(request, *args, **kwargs)

blog/blog/templates/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Django Web Programming{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">



    {% block extra-style %}{% endblock %}
</head>


<body style="padding-top:90px;">
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
  <span class="navbar-brand mx-5 mb-0 font-weight-bold font-italic">Django - Python Web Programming</span>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item mx-1 btn btn-primary">
          <a class="nav-link text-white" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item mx-1 btn btn-primary">
          <a class="nav-link text-white" href="{% url 'bookmark:index' %}">Bookmark</a>
        </li>
        <li class="nav-item mx-1 btn btn-primary">
          <a class="nav-link text-white" href="{% url 'blog:index' %}">Blog</a>
        </li>
        <li class="nav-item mx-1 btn btn-primary">
          <a class="nav-link text-white" href="{% url 'photo:index' %}">Photo</a>
        </li>

        <li class="nav-item dropdown mx-1 btn btn-primary">
          <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
              Add</a>
          <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'bookmark:add' %}">Bookmark</a>
              <a class="dropdown-item" href="{% url 'blog:add' %}">Post</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'photo:album_add' %}">Album</a>
              <a class="dropdown-item" href="{% url 'photo:photo_add' %}">Photo</a>
              </div>
        </li>


        <li class="nav-item dropdown mx-1 btn btn-primary">
          <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
              Change</a>
          <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'bookmark:change' %}">Bookmark</a>
              <a class="dropdown-item" href="{% url 'blog:change' %}">Post</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'photo:album_change' %}">Album</a>
              <a class="dropdown-item" href="{% url 'photo:photo_change' %}">Photo</a>
              </div>
        </li>


        <li class="nav-item dropdown mx-1 btn btn-primary">
          <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
            Util
          </a>
          <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'blog:post_archive' %}">Archive</a>
                <a class="dropdown-item" href="{% url 'blog:search' %}">Search</a>
              </div>
            </li>
          </ul>

      <form class="form-inline my-2" action="" method="post"> {% csrf_token %}
        <input class="form-control mr-sm-2" type="search" placeholder="global search" name="search_word">
      </form>


        <ul class="navbar-nav ml-5 mr-5">
            <li class="nav-item dropdown mx-1 btn btn-primary">
                {% if user.is_active %}
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                    <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;</a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
                <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
                </div>
                {% else %}
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                    <i class="fas fa-user"></i>&ensp;Anonymous&ensp;</a>
                <div class="dropdown-menu">
                    <a class="dropdown-item" href="{% url 'login' %}">Login</a>
                    <a class="dropdown-item" href="{% url 'register' %}">Register</a>
                    </div>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

{% block footer %}{% endblock %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://kit.fontawesome.com/772c5ea586.js"></script>

 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
 <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
 <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>


{% block extra-script %}{% endblock %}
</body>
</html>

blog/blog/templates/home.html
{% extends 'base.html' %}
{% block title %}home.html{% endblock %}
{% block content %}
    <h4>This is CONTENT area.</h4>
{% endblock %}
{% block footer %}
    <footer class="fixed-bottom bg-info">
        <h4>This is FOOTER area.</h4>
    </footer>
{% endblock %}